### PR TITLE
WOS filter databases

### LINKED ISSUE #419: Limit results to WoS and Medline editions only
We are currently searching all databases using the WoK database identifier.  We want to limit results to only WoS and Medline results to prevent issues with parsing of other databases and potential duplication issues.  Clarivate tells us that using the <editions> filter does not work with limiting to specific databases.  Even though we only expect to get back WoS or MEDLINE records, we should filter against other types of records (e.g. CCC) just to be sure.

This could be a no-op -- if the code doesn't break when an unknown record is encountered, we could log this and ignore the record.  That is acceptable and this issue could then be closed. 

- [ ] can be done in the harvester/processor code (https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/process_records.rb)

### PR DESCRIPTION
**Pull request by darrenleeweber**
Fix #419 

Selects only WOS & MEDLINE records for processing, using a configuration setting to specify what databases are allowed to be processed.

### CODE REVIEW

File: lib/web_of_science/process_records.rb [hunk 1]
```diff
@@ -43,12 +44,21 @@ def create_publications
...
+        return records if Settings.WOS.ACCEPTED_DBS.empty?
+        records.select { |rec| Settings.WOS.ACCEPTED_DBS.include? rec.database }
       end
 
       ## 2
+      # Filter and select new WebOfScienceSourceRecords
+      # @return [Array<WebOfScience::Record>]
+      def match_wos_records(records)
+        return [] if records.count.zero?
+        records.select { |rec| WebOfScienceSourceRecord.where(uid: rec.uid).count.zero? }
```
Comment (atz) [inline lib/web_of_science/process_records.rb]: For 100 records, these does 100 queries on `WebOfScienceSourceRecord`'s table when it could just do one.

File: spec/lib/web_of_science/process_records_spec.rb [hunk 2]
```diff
@@ -51,12 +51,10 @@
     # Happy paths
 
     it 'works' do
-      result = processor.execute
-      expect(result).not_to be_nil
+      expect(processor.execute).not_to be_nil
```
Comment (atz) [inline spec/lib/web_of_science/process_records_spec.rb]: 👍

File: lib/web_of_science/process_records.rb (hunk 1 above)
Comment (darrenleeweber) [reply lib/web_of_science/process_records.rb]: Yes, that change could be made, although it wasn't the focus of this PR.  I'll go ahead and try to resolve that anyway in this PR.

**Comment by darrenleeweber** [comment]
Pushed up more efficient filtering for existing WOS source records in f696ae07d5c8e95b7a84de9d5667bc2feea22f10
