### PR TITLE
Strips whitespace from year.

### LINKED ISSUE #1367: Invalid date when submitting work to ORCID
## Backtrace

    line 40 of [PROJECT_ROOT]/lib/orcid/client.rb: add_work
    line 41 of [PROJECT_ROOT]/lib/orcid/add_works.rb: add_work
    line 30 of [PROJECT_ROOT]/lib/orcid/add_works.rb: block in add_for_orcid_user

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/80045843)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1367

## Why was this change made?
So that work can be successfully submitted to ORCID.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

File: spec/lib/orcid/pub_mapper_spec.rb [hunk 1]
```diff
@@ -151,6 +151,23 @@
...
 
+  context 'when year has whitespace' do
+    let(:pub_hash) do
+      base_pub_hash.dup.tap do |pub_hash|
+        pub_hash.delete(:date)
+        pub_hash[:year] = ' 1950'
+      end
+    end
+
+    it 'does not map' do
```
Comment (jmartin-sul) [inline spec/lib/orcid/pub_mapper_spec.rb:162]: should title be more like `maps with whitespace stripped`?

**Review by jmartin-sul — CHANGES_REQUESTED** [review]
one tiny quibble about a test title but otherwise 👍

File: spec/lib/orcid/pub_mapper_spec.rb (hunk 1 above)
Comment (justinlittman) [reply spec/lib/orcid/pub_mapper_spec.rb:162]: Thanks for catching. I had originally had it not map then changed the functionality.

**Review by jmartin-sul — APPROVED** [review]
