### PR TITLE
Cap::Client - use Faraday and VCR specs

### LINKED ISSUE #458: Remove unused and not working cap http client API call
Double check what the CAP-API call is to get an author via sunetid?  We are getting back too many results for this query, e.g.
```
https://cap-dev.stanford.edu/cap-api/api/cap/v1/authors?uids=furmand
```

That authors API call should match the same result we get back from this call
```
https://cap-dev.stanford.edu/cap-api/api/cap/v1/authors/9957
```

### LINKED ISSUE #496: Fix "method_complexity" issue in lib/cap_http_client.rb
Method `make_cap_request` has a Cognitive Complexity of 16 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sul-dlss/sul_pub/lib/cap_http_client.rb#issue_5a2583e02c7fa200010000fd

### LINKED ISSUE #497: Fix "method_lines" issue in lib/cap_http_client.rb
Method `make_cap_request` has 39 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/sul-dlss/sul_pub/lib/cap_http_client.rb#issue_5a2583e02c7fa200010000fe

### LINKED ISSUE #498: Fix "method_complexity" issue in lib/cap_http_client.rb
Method `generate_token` has a Cognitive Complexity of 7 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sul-dlss/sul_pub/lib/cap_http_client.rb#issue_5a2583e02c7fa200010000fc

### LINKED ISSUE #499: Fix "similar-code" issue in lib/cap_http_client.rb
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/sul-dlss/sul_pub/lib/cap_http_client.rb#issue_5a2583e52c7fa2000100012f

### PR DESCRIPTION
**Pull request by darrenleeweber**
Fix #458
Fix #496
Fix #497
Fix #498
Fix #499 

- move CAP-API code into a `Cap` module
- use Faraday for the `Cap::Client`
- should fix some code-smells identified by code-climate
  - fixed issues in the `Cap::Client`

### Dependencies
Connected to #490 

### Notes
- there is no attempt here to fix anything for the existing cap client that will be replaced by this new client; the original PR did all those fixes and replaced the old client, that will now be done in #537

### CODE REVIEW

**Comment by darrenleeweber** [comment]
### Updates:
- All ENV removed from https://travis-ci.org/sul-dlss/sul_pub/settings
- this PR is now focused on a new `Cap::Client`
  - additional work to use this client and replace the old client will be done in #537

File: spec/spec_helper.rb [hunk 1]
```diff
@@ -99,25 +99,46 @@
...
+  end
+  c.filter_sensitive_data('private_access_token') do |interaction|
+    if interaction.request.uri.include? Settings.CAP.TOKEN_PATH
+      token_match = interaction.response.body.match(/"access_token":"(.*?)"/)
+      token_match.captures.first if token_match
+    end
+  end
+  c.filter_sensitive_data('CAP-LicenseID') do |interaction|
+    if interaction.request.uri.include? Settings.CAP.AUTHORSHIP_API_PATH
+      id_match = interaction.response.body.match(/"californiaPhysicianLicense".*?:.*?"(.*?)"/)
```
Comment (atz) [inline spec/spec_helper.rb]: why do we need to filter `californiaPhysicianLicense`?  I thought that was a publicly available identifier.

File: spec/spec_helper.rb [hunk 2]
```diff
@@ -99,25 +99,46 @@
...
+      bearer = auth.select { |a| a =~ /bearer/i }.first
       bearer.gsub(/bearer /i, '') if bearer
     end
   end
   c.filter_sensitive_data('Settings.SCIENCEWIRE.HOST') { Settings.SCIENCEWIRE.HOST }
   c.filter_sensitive_data('Settings.SCIENCEWIRE.LICENSE_ID') { Settings.SCIENCEWIRE.LICENSE_ID }
+
+  # CAP API filters
+  c.filter_sensitive_data('Settings.CAP.TOKEN_URI') { Settings.CAP.TOKEN_URI }
+  c.filter_sensitive_data('Settings.CAP.AUTHORSHIP_API_URI') { Settings.CAP.AUTHORSHIP_API_URI }
```
Comment (atz) [inline spec/spec_helper.rb]: I think this 2 URLs are not sensitive.  Am I missing something?

File: spec/spec_helper.rb (hunk 1 above)
Comment (peetucket) [reply spec/spec_helper.rb]: this filters it out of vcr_cassettes?  I don't think we necessarily need to follow the rule of if it can be public, we should store in our repo (seeing as it takes little effort to remove).   I can see some physicians (or anyone really) wanting to limit the number of places their personal information is stored (even public personal info) and so no need to add to that list of places for them
