### PR TITLE
WebOfScience::ProcessPubmed enhancements

### LINKED ISSUE #640: WOS Harvest exception for PMID: 27963929
Failed to find a PubMed record in
- `/lib/web_of_science/process_records.rb:117`
- `pubmed_record = PubmedSourceRecord.for_pmid(record.pmid)`
- `Author: 6, WOS:000276606606255, PubmedSourceRecord failed, PMID: 27963929`

At this point in the harvest, this WOS record contribution for this author already exists.  When the harvest runs again, it will skip this WOS record.  In this scenario, the harvest will never touch this record again.  If there is a PMID record that exists, it will never get integrated by the harvest.  If it doesn't exist, that explains the failure (it's a WOS/Medline data problem?).  The harvest process is designed to be resilient to this failure, it should isolate this exception to just that record and continue (this appears to be true but could be confirmed in some sandbox testing).

#### Note
When calling `PubmedSourceRecord.for_pmid(record.pmid)`, it tries to find it in our records or fetch it from PubMed, i.e.
```
  def self.for_pmid(pmid)
    find_by(pmid: pmid) || get_pubmed_record_from_pubmed(pmid)
  end
```

#### Backtrace

This exception should be registered with Honeybager, but it didn't make it there:
- https://app.honeybadger.io/projects/50046/faults?sort=last_seen_desc&q=environment%3A%22development%22

```
E, [2018-01-19T18:10:39.337083 #11131] ERROR -- : WebOfScience::ProcessRecords: Author: 6, WOS:000276606606255, PubmedSourceRecord failed, PMID: 27963929
E, [2018-01-19T18:10:39.346585 #11131] ERROR -- : #<NoMethodError: undefined method `source_as_hash' for nil:NilClass>
E, [2018-01-19T18:10:39.346828 #11131] ERROR -- : /opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:117:in `pubmed_addition'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:104:in `block in pubmed_additions'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:104:in `each'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:104:in `pubmed_additions'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:47:in `create_publications'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:22:in `execute'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:91:in `process_records'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:78:in `process_uids'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:33:in `process_author'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:16:in `block in harvest'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:15:in `each'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:15:in `harvest'
/opt/app/pub/sul-pub/releases/20180120002105/lib/harvester/base.rb:9:in `block in harvest_all'
```

### PR DESCRIPTION
**Pull request by darrenleeweber**
Fix #640 & https://app.honeybadger.io/projects/50046/faults/36312445#notice-summary
- extract module to process pubmed enhancements
  - the new public methods need additional specs
- WOS data contains hundreds of missing/bad PMID values, when it's bad:
  - remove the PMID from the Publication and PublicationIdentifier data
  - but when the PubMed API is not responsive, don't cleanup any PMIDs

### CODE REVIEW

File: lib/web_of_science/process_pubmed.rb [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+      NotificationManager.error(err, message, self)
+    end
+
+    # For WOS-record that has a PMID, cleanup our data when it does not exist on PubMed
+    # @param [WebOfScience::Record] record
+    # @param [Publication] pub
+    # @return [void]
+    def pubmed_missing(record, pub)
+      WebOfScience.logger.warn "#{record.uid}, PubmedSourceRecord missing, PMID: #{record.pmid}"
+      return unless PubmedClient.working?
```
Comment (peetucket) [inline lib/web_of_science/process_pubmed.rb]: this makes another round trip to Pubmed each time, which seems uncessary and may start to get expensive particularly when it actually being down has proved to be extremely rare... 

is there any way to tell from the PubmedSourceRecord.for_pmid call before this if the nil result was because nothing was found or because Pubmed was down?

Comment (atz) [reply lib/web_of_science/process_pubmed.rb]: Yes, `working?` makes a round-trip.  But if it is only rarely expensive, that doesn't seem like a dealbreaker.

Comment (peetucket) [reply lib/web_of_science/process_pubmed.rb]: yeah, i realize that'll probably be rare too (hopefully, assuming WoS data is mostly correct) so not a dealbreaker

Comment (darrenleeweber) [reply lib/web_of_science/process_pubmed.rb]: In the partial WOS-harvest, there were hundreds of bogus PMID.  It would be poor of us to mirror bad data in our Pub and Pub-Ids.  The round trip cost to check on the status of PubMed API seems to be essential though to prevent removing good PMID data.  There are a multitude of cost/benefit aspects to this, but mostly data integrity seems more important than performance hits.

Comment (atz) [reply lib/web_of_science/process_pubmed.rb]: If possible, can we get a logging (ideally at aggregate level) of how many bad PMIDs we detect?  This seems important to characterize our confidence/skepticism about WOS PMIDS and might be useful feedback to Clarivate.
