### PR TITLE
Fix issue with first names; add better exception for HB

### LINKED ISSUE #1149: Authors with a period for a first name cause a blank name query clause to be generated
This author currently has a period for a first name, causing a blank name clause `AU` to be generated.  We should at least put their last name (which does exist) in the name clause to avoid creating too many publication results or even better, skip the query entirely if it would be nothing.

```
author=Author.find(53490)
puts "CAP_PROFILE_ID: #{author.cap_profile_id}";puts "NUM PUBS: #{author.contributions.count}";puts "PRIMARY AUTHOR NAME: #{author.cap_first_name} #{author.cap_last_name}";author_query = WebOfScience::QueryAuthor.new(author);puts "ALL NAMES: #{author_query.send(:names).join(";")}";puts "INSTITUTIONS: #{author_query.send(:institutions).join(";")}";puts "WOS: #{author_query.send(:author_query)[:queryParameters][:userQuery]}";pm_query = Pubmed::QueryAuthor.new(author, {});puts "Pubmed: #{pm_query.send(:term)}";nil
CAP_PROFILE_ID: 69115
NUM PUBS: 1
PRIMARY AUTHOR NAME: . Rituraj
ALL NAMES:
INSTITUTIONS: stanford
WOS: AU=() AND AD=("stanford")
Pubmed: () AND (Stanford University[Affiliation])
=> nil
```

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

fixes #1149 and #1150

Basically we want to guard against invalid queries when harvesting so we don't create too many publications.

This PR also adds a guard against too many publications for WoS harvesting the same way we currently guard against too many publications for pubmed harvesting (just in case we are missing other edge cases that would generate too many publications).

Basically, look at the name query for any given authors, and if's blank call it invalid, and then skip over the author when harvesting.

It also adds a new exception class for harvesting errors so its easier to see what the actual exception is in HB (previously an error from harvesting was reported as "StandardError" and you had to dig down into the "context" to see what actually was being reported, which is easy to miss).

## Does this change affect how this application integrates with other services?
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.

### CODE REVIEW

File: spec/factories/author.rb [hunk 1]
```diff
@@ -54,6 +54,32 @@
     end
   end
 
+  factory :period_first_name_author, parent: :author do
```
Comment (jcoyne) [inline spec/factories/author.rb]: Have you considered using traits for this?

File: spec/lib/pubmed/harvester_spec.rb [hunk 2]
```diff
@@ -21,6 +22,7 @@
       let(:pmid) { '30833575' }
       before do
         allow(Pubmed::QueryAuthor).to receive_message_chain(:new, :pmids).and_return([pmid])
```
Comment (jcoyne) [inline spec/lib/pubmed/harvester_spec.rb]: How about returning a stub QueryAuthor from new rather than several stub chains?

File: spec/lib/pubmed/harvester_spec.rb [hunk 3]
```diff
@@ -33,8 +35,26 @@
 
     context 'when author query has too many publications' do
       let(:lotsa_pmids) { Array(1..Settings.PUBMED.max_publications_per_author) }
+      let(:query_author) { instance_double(Pubmed::QueryAuthor) }
+
+      before do
+        allow(Pubmed::QueryAuthor).to receive(:new).with(author, {}).and_return(query_author)
+        allow(query_author).to receive(:pmids).and_return(lotsa_pmids)
```
Comment (jcoyne) [inline spec/lib/pubmed/harvester_spec.rb]: You can incorporate these lines into the instance_double call

File: spec/lib/pubmed/harvester_spec.rb [hunk 4]
```diff
@@ -33,8 +35,26 @@
...
+      end
+    end
+
+    context 'when author query is invalid' do
+      let(:query_author) { instance_double(Pubmed::QueryAuthor) }
+
       before do
-        allow(Pubmed::QueryAuthor).to receive_message_chain(:new, :pmids).and_return(lotsa_pmids)
+        allow(Pubmed::QueryAuthor).to receive(:new).with(author, {}).and_return(query_author)
+        allow(query_author).to receive('valid?').and_return(false)
```
Comment (jcoyne) [inline spec/lib/pubmed/harvester_spec.rb]: Roll this into the instance double

File: spec/lib/web_of_science/harvester_spec.rb [hunk 5]
```diff
@@ -136,4 +136,34 @@
...
     end
   end
+
+  context 'when author query has too many publications' do
+    let(:lotsa_uids) { Array(1..Settings.WOS.max_publications_per_author) }
+    let(:query_author) { instance_double(WebOfScience::QueryAuthor) }
+
+    before do
+      allow(WebOfScience::QueryAuthor).to receive(:new).with(author, {}).and_return(query_author)
+      allow(query_author).to receive(:uids).and_return(lotsa_uids)
```
Comment (jcoyne) [inline spec/lib/web_of_science/harvester_spec.rb]: These lines can roll into the instance_double

File: spec/factories/author.rb (hunk 1 above)
Comment (peetucket) [reply spec/factories/author.rb]: just learned about this, adjusted to use

File: spec/lib/pubmed/harvester_spec.rb (hunk 2 above)
Comment (peetucket) [reply spec/lib/pubmed/harvester_spec.rb]: adjusted

File: spec/lib/pubmed/harvester_spec.rb (hunk 4 above)
Comment (peetucket) [reply spec/lib/pubmed/harvester_spec.rb]: done

File: spec/lib/web_of_science/harvester_spec.rb (hunk 5 above)
Comment (peetucket) [reply spec/lib/web_of_science/harvester_spec.rb]: done

File: spec/lib/pubmed/harvester_spec.rb (hunk 3 above)
Comment (peetucket) [reply spec/lib/pubmed/harvester_spec.rb]: done
