### PR TITLE
truncate long abstracts when mapping to orcid

### LINKED ISSUE #1383: [sul_pub/prod] ORCID.org API returned 400
```({"response-code":400,"developer-message":"400 Bad request: invalid JSON - cvc-maxLength-valid: Value 'DISCLOSURES: Sharman: AbbVie: Consultancy, Honoraria, Research Funding; Genentech: Consultancy, Honoraria, Research Funding; TG Therapeutics: Consultancy, Honoraria, Research Funding; Pharmacyclics LLC, an AbbVie Company: Consultancy, Honoraria, Research Funding; Acerta: Consultancy, Honoraria, Research Funding; AstraZeneca: Consultancy, Honoraria,...
```

## Backtrace

    line 40 of [PROJECT_ROOT]/lib/orcid/client.rb: add_work
    line 41 of [PROJECT_ROOT]/lib/orcid/add_works.rb: add_work
    line 30 of [PROJECT_ROOT]/lib/orcid/add_works.rb: block in add_for_orcid_user

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/80045843)

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

Fixes #1383 - long abstracts need to be truncated when pushing to ORCID to fit their Works data model

Note: this is the publication we will want to try and push again when deployed, publication_id = 797885, cap_profile_id = 247934, sunet_id = ajdawes

```
p=Publication.find(797885)
p.pub_hash[:abstract].size
=> 5139
[6] pry(main)> p.contributions
=> [#<Contribution:0x00000000072a4890
  id: 1577149,
  author_id: 142648,
  cap_profile_id: 247934,
  publication_id: 797885,
  status: "approved",
  featured: false,
  visibility: "public",
  created_at: Fri, 06 Nov 2020 12:26:52 UTC +00:00,
  updated_at: Sat, 07 Nov 2020 12:13:36 UTC +00:00,
  orcid_put_code: nil>]
p.contributions.first.author
=> #<Author:0x0000000007093e70
 id: 142648,
 cap_profile_id: 247934,
 sunetid: 'ajdawes',
....
```

We can re-run the works like this:

```
RAILS_ENV=production bundle exec rake orcid:add_author_works['ajdawes']
```

## How was this change tested?

Added new unit tests

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

File: spec/lib/orcid/pub_mapper_spec.rb [hunk 1]
```diff
@@ -168,6 +168,34 @@
     end
   end
 
+  context 'with abstract greater than 5000 characters' do
+    let(:big_abstract) { SecureRandom.random_number(36**6000).to_s(36) } # generates 6000 character random string
+
+    let(:pub_hash) do
+      base_pub_hash.dup.tap do |pub_hash|
```
Comment (jcoyne) [inline spec/lib/orcid/pub_mapper_spec.rb:175]: `.dup.tap` is basically same as `base_pub_hash.merge(abstract: big_abstract)`.  I think the merge format is more readable 🤷

Comment (peetucket) [reply spec/lib/orcid/pub_mapper_spec.rb]: makes sense -- i switched it

**Comment by peetucket** [comment]
Added works for this author and the publication that previously failed has now succeeded.
